/**
 * @module engine/terrain
 * @role Generate and render voxel terrain on JollyPixel VoxelRenderer
 * @input JollyPixel World, Rapier World, seed string
 * @output VoxelRenderer instance, surface height lookup
 */
import RAPIER from '@dimforge/rapier3d';
import { type BlockDefinition, Face, type TileRef, VoxelRenderer } from '@jolly-pixel/voxel.renderer';
import * as THREE from 'three';
import { PRNG, SimplexNoise } from '../generation/index.ts';
import { generateTileset, TILES } from '../rendering/TilesetGenerator.ts';
import type { SurfaceHeightFn } from './types.ts';

// --- Block Definitions ---
const BLOCK_DEFS: BlockDefinition[] = [
  {
    id: 1,
    name: 'Grass',
    shapeId: 'cube',
    collidable: true,
    faceTextures: { [Face.PosY]: TILES.GRASS_TOP as TileRef, [Face.NegY]: TILES.DIRT as TileRef },
    defaultTexture: TILES.DIRT as TileRef,
  },
  {
    id: 2,
    name: 'Dirt',
    shapeId: 'cube',
    collidable: true,
    faceTextures: {},
    defaultTexture: TILES.DIRT as TileRef,
  },
  {
    id: 3,
    name: 'Stone',
    shapeId: 'cube',
    collidable: true,
    faceTextures: {},
    defaultTexture: TILES.STONE as TileRef,
  },
  {
    id: 4,
    name: 'Water',
    shapeId: 'cube',
    collidable: false,
    faceTextures: {},
    defaultTexture: TILES.WATER as TileRef,
  },
  {
    id: 5,
    name: 'Sand',
    shapeId: 'cube',
    collidable: true,
    faceTextures: {},
    defaultTexture: TILES.SAND as TileRef,
  },
  {
    id: 6,
    name: 'Wood',
    shapeId: 'cube',
    collidable: true,
    faceTextures: { [Face.PosY]: TILES.WOOD_TOP as TileRef, [Face.NegY]: TILES.WOOD_TOP as TileRef },
    defaultTexture: TILES.WOOD_SIDE as TileRef,
  },
  {
    id: 7,
    name: 'Leaves',
    shapeId: 'cube',
    collidable: false,
    faceTextures: {},
    defaultTexture: TILES.LEAVES as TileRef,
  },
];

const ISLAND_SIZE = 48;
const BASE_HEIGHT = 4;
const NOISE_AMP = 6;

export interface TerrainResult {
  voxelMap: any; // VoxelRenderer component instance
  getSurfaceY: SurfaceHeightFn;
  islandSize: number;
  baseHeight: number;
}

/**
 * Create and populate the voxel terrain.
 * Generates blocks, water, trees from a seed. Builds surface height lookup.
 * Rapier terrain colliders are auto-generated by VoxelRenderer's VoxelColliderBuilder.
 */
export function createTerrain(jpWorld: any, rapierWorld: RAPIER.World, seed: string): TerrainResult {
  // Create VoxelRenderer actor with Rapier physics
  const voxelMap = (jpWorld.createActor('terrain') as any).addComponentAndGet(VoxelRenderer, {
    chunkSize: 16,
    layers: ['Ground'],
    blocks: BLOCK_DEFS,
    alphaTest: 0.5,
    material: 'lambert',
    rapier: {
      api: RAPIER as never,
      world: rapierWorld as never,
    },
  });

  // Generate and register programmatic tileset
  const tileset = generateTileset();
  const tilesetTexture = new THREE.Texture(tileset.canvas);
  tilesetTexture.magFilter = THREE.NearestFilter;
  tilesetTexture.minFilter = THREE.NearestFilter;
  tilesetTexture.needsUpdate = true;
  (voxelMap as any).tilesetManager.registerTexture(
    { id: 'game', src: tileset.dataUrl, tileSize: 32, cols: 3, rows: 3 },
    tilesetTexture as any,
  );

  // Generate terrain from seed
  const prng = new PRNG(seed);
  const noise = new SimplexNoise(prng);

  for (let x = 0; x < ISLAND_SIZE; x++) {
    for (let z = 0; z < ISLAND_SIZE; z++) {
      const dx = (x - ISLAND_SIZE / 2) / (ISLAND_SIZE / 2);
      const dz = (z - ISLAND_SIZE / 2) / (ISLAND_SIZE / 2);
      const falloff = 1 - Math.sqrt(dx * dx + dz * dz);
      if (falloff <= 0) continue;

      const noiseVal = noise.noise2D(x * 0.05, z * 0.05);
      const height = Math.floor(BASE_HEIGHT + noiseVal * NOISE_AMP * falloff);

      // Place terrain blocks
      for (let y = 0; y <= height; y++) {
        let blockId: number;
        if (y === height) {
          blockId = height <= 2 ? 5 : 1;
        } else if (y >= height - 2) {
          blockId = 2;
        } else {
          blockId = 3;
        }
        voxelMap.setVoxel('Ground', { position: { x, y, z }, blockId });
      }

      // Water
      if (height < 2) {
        for (let y = height + 1; y <= 2; y++) {
          voxelMap.setVoxel('Ground', { position: { x, y, z }, blockId: 4 });
        }
      }

      // Trees
      if (height > 3 && prng.next() > 0.95 && falloff > 0.3) {
        const treeHeight = 3 + Math.floor(prng.next() * 3);
        for (let ty = 1; ty <= treeHeight; ty++) {
          voxelMap.setVoxel('Ground', { position: { x, y: height + ty, z }, blockId: 6 });
        }
        for (let lx = -2; lx <= 2; lx++) {
          for (let lz = -2; lz <= 2; lz++) {
            for (let ly = 0; ly <= 2; ly++) {
              if (Math.abs(lx) + Math.abs(lz) + ly <= 3 && (lx !== 0 || lz !== 0 || ly > 0)) {
                const leafX = x + lx;
                const leafZ = z + lz;
                const leafY = height + treeHeight + ly;
                if (leafX >= 0 && leafX < ISLAND_SIZE && leafZ >= 0 && leafZ < ISLAND_SIZE) {
                  voxelMap.setVoxel('Ground', { position: { x: leafX, y: leafY, z: leafZ }, blockId: 7 });
                }
              }
            }
          }
        }
      }
    }
  }

  // Build surface height lookup
  const surfaceHeight = new Map<string, number>();
  for (let x = 0; x < ISLAND_SIZE; x++) {
    for (let z = 0; z < ISLAND_SIZE; z++) {
      for (let y = 20; y >= 0; y--) {
        const voxel = voxelMap.getVoxel('Ground', { x, y, z });
        if (voxel && voxel.blockId !== 4 && voxel.blockId !== 7) {
          surfaceHeight.set(`${x},${z}`, y + 1);
          break;
        }
      }
    }
  }

  function getSurfaceY(x: number, z: number): number {
    return surfaceHeight.get(`${Math.round(x)},${Math.round(z)}`) ?? BASE_HEIGHT + 1;
  }

  return { voxelMap, getSurfaceY, islandSize: ISLAND_SIZE, baseHeight: BASE_HEIGHT };
}
