/**
 * @module engine/terrainSetup
 * @role Generate and render biome-aware voxel terrain on JollyPixel VoxelRenderer
 * @input JollyPixel World, Rapier World, seed string, biome ID
 * @output VoxelRenderer instance, surface height lookup
 */
import RAPIER from '@dimforge/rapier3d';
import { VoxelRenderer } from '@jolly-pixel/voxel.renderer';
import * as THREE from 'three';
import { ContentRegistry } from '../content/index.ts';
import { PRNG, SimplexNoise } from '../generation/index.ts';
import { generateTileset, TILESET_COLS, TILESET_ROWS } from '../rendering/index';
import { getBiomeBlockDefs } from './biomeBlocks.ts';
import type { JpWorld, SurfaceHeightFn } from './types.ts';

const ISLAND_SIZE = 48;

export interface TerrainResult {
  voxelMap: VoxelRenderer;
  getSurfaceY: SurfaceHeightFn;
  islandSize: number;
  baseHeight: number;
}

/**
 * Create and populate the voxel terrain.
 * Reads biome config from ContentRegistry to drive noise params and block selection.
 * Rapier terrain colliders are auto-generated by VoxelRenderer's VoxelColliderBuilder.
 */
export function createTerrain(
  jpWorld: JpWorld,
  rapierWorld: RAPIER.World,
  seed: string,
  biomeId: string,
): TerrainResult {
  // --- Load biome config ---
  const content = new ContentRegistry();
  const biome = content.getBiome(biomeId);
  const terrainConfig = biome.terrain;

  const noiseAmp = terrainConfig.noiseAmplitude;
  const baseHeight = terrainConfig.baseHeight;
  const noiseFreq = terrainConfig.noiseFrequency;
  const waterLevel = terrainConfig.waterLevel;
  const surfaceBlockId = terrainConfig.blocks.surface;
  const subsurfaceBlockId = terrainConfig.blocks.subsurface;
  const stoneBlockId = terrainConfig.blocks.stone;
  const waterBlockId = terrainConfig.blocks.water ?? 4; // fallback to base water
  const accentBlockId = terrainConfig.blocks.accent;

  // --- Block definitions ---
  const blockDefs = getBiomeBlockDefs(biomeId);

  // Create VoxelRenderer actor with Rapier physics
  const voxelMap = jpWorld.createActor('terrain').addComponentAndGet(VoxelRenderer, {
    chunkSize: 16,
    layers: ['Ground'],
    blocks: blockDefs,
    alphaTest: 0.5,
    material: 'lambert',
    rapier: {
      api: RAPIER as never,
      world: rapierWorld as never,
    },
  });

  // Generate and register programmatic tileset
  const tileset = generateTileset();
  const tilesetTexture = new THREE.Texture(tileset.canvas);
  tilesetTexture.magFilter = THREE.NearestFilter;
  tilesetTexture.minFilter = THREE.NearestFilter;
  tilesetTexture.needsUpdate = true;
  voxelMap.tilesetManager.registerTexture(
    { id: 'game', src: tileset.dataUrl, tileSize: 32, cols: TILESET_COLS, rows: TILESET_ROWS },
    tilesetTexture as unknown as THREE.Texture<HTMLImageElement>,
  );

  // Generate terrain from seed
  const prng = new PRNG(seed);
  const noise = new SimplexNoise(prng);

  // Max height for surface lookup scan
  const maxScanHeight = Math.ceil(baseHeight + noiseAmp + 20);

  for (let x = 0; x < ISLAND_SIZE; x++) {
    for (let z = 0; z < ISLAND_SIZE; z++) {
      const dx = (x - ISLAND_SIZE / 2) / (ISLAND_SIZE / 2);
      const dz = (z - ISLAND_SIZE / 2) / (ISLAND_SIZE / 2);
      const falloff = 1 - Math.sqrt(dx * dx + dz * dz);
      if (falloff <= 0) continue;

      const noiseVal = noise.noise2D(x * noiseFreq, z * noiseFreq);
      const height = Math.floor(baseHeight + noiseVal * noiseAmp * falloff);

      // --- Sky Ruins: create gaps in terrain for floating island effect ---
      if (biomeId === 'sky-ruins') {
        const gapNoise = noise.noise2D(x * 0.15, z * 0.15);
        if (gapNoise < -0.3 && falloff < 0.7) {
          continue; // skip this column entirely — creates void gaps
        }
      }

      // Place terrain blocks using biome-configured block IDs
      for (let y = 0; y <= height; y++) {
        let blockId: number;
        if (y === height) {
          // Surface block — use sand/beach near water level for forest biome
          if (biomeId === 'forest' && height <= waterLevel) {
            blockId = 5; // sand at shoreline
          } else {
            blockId = surfaceBlockId;
          }
        } else if (y >= height - 2) {
          blockId = subsurfaceBlockId;
        } else {
          blockId = stoneBlockId;
        }
        voxelMap.setVoxel('Ground', { position: { x, y, z }, blockId });
      }

      // Water/lava fill below water level
      if (height < waterLevel) {
        for (let y = height + 1; y <= waterLevel; y++) {
          voxelMap.setVoxel('Ground', { position: { x, y, z }, blockId: waterBlockId });
        }
      }

      // --- Biome-specific features ---
      generateBiomeFeatures(voxelMap, biomeId, x, z, height, falloff, waterLevel, prng, accentBlockId);
    }
  }

  // Build surface height lookup
  const surfaceHeight = new Map<string, number>();
  for (let x = 0; x < ISLAND_SIZE; x++) {
    for (let z = 0; z < ISLAND_SIZE; z++) {
      for (let y = maxScanHeight; y >= 0; y--) {
        const voxel = voxelMap.getVoxel('Ground', { x, y, z });
        if (voxel && voxel.blockId !== waterBlockId && voxel.blockId !== 4 && voxel.blockId !== 7) {
          surfaceHeight.set(`${x},${z}`, y + 1);
          break;
        }
      }
    }
  }

  function getSurfaceY(x: number, z: number): number {
    return surfaceHeight.get(`${Math.round(x)},${Math.round(z)}`) ?? baseHeight + 1;
  }

  return { voxelMap, getSurfaceY, islandSize: ISLAND_SIZE, baseHeight };
}

/**
 * Generate biome-specific decoration features (trees, cacti, crystals, etc.)
 */
function generateBiomeFeatures(
  voxelMap: VoxelRenderer,
  biomeId: string,
  x: number,
  z: number,
  height: number,
  falloff: number,
  waterLevel: number,
  prng: PRNG,
  _accentBlockId: number | undefined,
): void {
  switch (biomeId) {
    case 'forest':
      generateForestFeatures(voxelMap, x, z, height, falloff, waterLevel, prng);
      break;
    case 'desert':
      generateDesertFeatures(voxelMap, x, z, height, falloff, waterLevel, prng);
      break;
    case 'tundra':
      generateTundraFeatures(voxelMap, x, z, height, falloff, waterLevel, prng);
      break;
    case 'volcanic':
      generateVolcanicFeatures(voxelMap, x, z, height, falloff, waterLevel, prng);
      break;
    case 'swamp':
      generateSwampFeatures(voxelMap, x, z, height, falloff, waterLevel, prng);
      break;
    case 'crystal-caves':
      generateCrystalFeatures(voxelMap, x, z, height, falloff, waterLevel, prng);
      break;
    case 'sky-ruins':
      generateSkyFeatures(voxelMap, x, z, height, falloff, prng);
      break;
    case 'deep-ocean':
      generateOceanFeatures(voxelMap, x, z, height, falloff, waterLevel, prng);
      break;
  }
}

/** Forest: standard trees with dense canopy */
function generateForestFeatures(
  voxelMap: VoxelRenderer,
  x: number,
  z: number,
  height: number,
  falloff: number,
  waterLevel: number,
  prng: PRNG,
): void {
  if (height > waterLevel && prng.next() > 0.92 && falloff > 0.3) {
    const treeHeight = 3 + Math.floor(prng.next() * 3);
    for (let ty = 1; ty <= treeHeight; ty++) {
      voxelMap.setVoxel('Ground', { position: { x, y: height + ty, z }, blockId: 6 });
    }
    placeLeafCanopy(voxelMap, x, z, height + treeHeight, 2);
  }
}

/** Desert: cacti instead of trees, occasional oasis pools */
function generateDesertFeatures(
  voxelMap: VoxelRenderer,
  x: number,
  z: number,
  height: number,
  falloff: number,
  waterLevel: number,
  prng: PRNG,
): void {
  // Cacti (tall, no canopy)
  if (height > waterLevel && prng.next() > 0.96 && falloff > 0.3) {
    const cactusHeight = 2 + Math.floor(prng.next() * 3);
    for (let ty = 1; ty <= cactusHeight; ty++) {
      voxelMap.setVoxel('Ground', { position: { x, y: height + ty, z }, blockId: 14 });
    }
    // Optional cactus arm
    if (prng.next() > 0.5 && cactusHeight >= 3) {
      const armDir = prng.next() > 0.5 ? 1 : -1;
      const armY = height + Math.floor(cactusHeight * 0.6);
      const armX = x + armDir;
      if (armX >= 0 && armX < ISLAND_SIZE) {
        voxelMap.setVoxel('Ground', { position: { x: armX, y: armY, z }, blockId: 14 });
        voxelMap.setVoxel('Ground', { position: { x: armX, y: armY + 1, z }, blockId: 14 });
      }
    }
  }
}

/** Tundra: no trees, ice patches on flat areas, snow-covered peaks */
function generateTundraFeatures(
  voxelMap: VoxelRenderer,
  x: number,
  z: number,
  height: number,
  falloff: number,
  waterLevel: number,
  prng: PRNG,
): void {
  // Ice patches on flat areas near water
  if (height === waterLevel && prng.next() > 0.6 && falloff > 0.2) {
    voxelMap.setVoxel('Ground', { position: { x, y: height + 1, z }, blockId: 22 });
  }
  // Permafrost boulders on high ground
  if (height > waterLevel + 3 && prng.next() > 0.97 && falloff > 0.4) {
    voxelMap.setVoxel('Ground', { position: { x, y: height + 1, z }, blockId: 24 });
    if (prng.next() > 0.5) {
      voxelMap.setVoxel('Ground', { position: { x, y: height + 2, z }, blockId: 24 });
    }
  }
}

/** Volcanic: obsidian pillars, no vegetation */
function generateVolcanicFeatures(
  voxelMap: VoxelRenderer,
  x: number,
  z: number,
  height: number,
  falloff: number,
  waterLevel: number,
  prng: PRNG,
): void {
  // Obsidian pillars — tall, thin
  if (height > waterLevel + 1 && prng.next() > 0.97 && falloff > 0.3) {
    const pillarHeight = 2 + Math.floor(prng.next() * 4);
    for (let ty = 1; ty <= pillarHeight; ty++) {
      voxelMap.setVoxel('Ground', { position: { x, y: height + ty, z }, blockId: 30 });
    }
  }
  // Magma crust patches near lava
  if (height === waterLevel && prng.next() > 0.5) {
    voxelMap.setVoxel('Ground', { position: { x, y: height, z }, blockId: 34 });
  }
}

/** Swamp: dead trees (short, no leaves), extensive shallow water */
function generateSwampFeatures(
  voxelMap: VoxelRenderer,
  x: number,
  z: number,
  height: number,
  falloff: number,
  waterLevel: number,
  prng: PRNG,
): void {
  // Dead trees — short stumps with no canopy
  if (height > waterLevel && prng.next() > 0.93 && falloff > 0.25) {
    const stumpHeight = 1 + Math.floor(prng.next() * 2);
    for (let ty = 1; ty <= stumpHeight; ty++) {
      voxelMap.setVoxel('Ground', { position: { x, y: height + ty, z }, blockId: 44 });
    }
  }
}

/** Crystal Caves: crystal pillars (tall thin columns), geode formations */
function generateCrystalFeatures(
  voxelMap: VoxelRenderer,
  x: number,
  z: number,
  height: number,
  falloff: number,
  waterLevel: number,
  prng: PRNG,
): void {
  // Crystal pillars — tall, thin columns of amethyst
  if (height > waterLevel && prng.next() > 0.95 && falloff > 0.3) {
    const pillarHeight = 3 + Math.floor(prng.next() * 5);
    for (let ty = 1; ty <= pillarHeight; ty++) {
      const blockId = ty <= 1 ? 51 : 52; // geode base, amethyst shaft
      voxelMap.setVoxel('Ground', { position: { x, y: height + ty, z }, blockId });
    }
    // Quartz cap
    voxelMap.setVoxel('Ground', { position: { x, y: height + pillarHeight + 1, z }, blockId: 54 });
  }
  // Geode formations (small clusters)
  if (height > waterLevel + 1 && prng.next() > 0.97 && falloff > 0.4) {
    voxelMap.setVoxel('Ground', { position: { x, y: height + 1, z }, blockId: 51 });
    if (prng.next() > 0.5) {
      voxelMap.setVoxel('Ground', { position: { x, y: height + 2, z }, blockId: 52 });
    }
  }
}

/** Sky Ruins: floating cloud edges, wind blocks at perimeter */
function generateSkyFeatures(
  voxelMap: VoxelRenderer,
  x: number,
  z: number,
  height: number,
  falloff: number,
  prng: PRNG,
): void {
  // Cloud wisps at edges
  if (falloff > 0.1 && falloff < 0.35 && prng.next() > 0.7) {
    voxelMap.setVoxel('Ground', { position: { x, y: height + 1, z }, blockId: 60 });
  }
  // Wind block accent pillars
  if (height > 8 && prng.next() > 0.98 && falloff > 0.4) {
    const pillarH = 1 + Math.floor(prng.next() * 3);
    for (let ty = 1; ty <= pillarH; ty++) {
      voxelMap.setVoxel('Ground', { position: { x, y: height + ty, z }, blockId: 64 });
    }
  }
}

/** Ocean: coral patches, kelp strands, small above-water formations */
function generateOceanFeatures(
  voxelMap: VoxelRenderer,
  x: number,
  z: number,
  height: number,
  falloff: number,
  waterLevel: number,
  prng: PRNG,
): void {
  // Coral on the sea floor (underwater accent)
  if (height < waterLevel - 1 && prng.next() > 0.9 && falloff > 0.3) {
    voxelMap.setVoxel('Ground', { position: { x, y: height + 1, z }, blockId: 70 });
  }
  // Kelp strands — tall underwater columns
  if (height < waterLevel - 2 && prng.next() > 0.95 && falloff > 0.3) {
    const kelpHeight = 1 + Math.floor(prng.next() * Math.min(3, waterLevel - height - 1));
    for (let ty = 1; ty <= kelpHeight; ty++) {
      voxelMap.setVoxel('Ground', { position: { x, y: height + ty, z }, blockId: 74 });
    }
  }
}

/** Places a diamond-shaped leaf canopy at the given tree top */
function placeLeafCanopy(voxelMap: VoxelRenderer, x: number, z: number, topY: number, radius: number): void {
  for (let lx = -radius; lx <= radius; lx++) {
    for (let lz = -radius; lz <= radius; lz++) {
      for (let ly = 0; ly <= 2; ly++) {
        if (Math.abs(lx) + Math.abs(lz) + ly <= 3 && (lx !== 0 || lz !== 0 || ly > 0)) {
          const leafX = x + lx;
          const leafZ = z + lz;
          const leafY = topY + ly;
          if (leafX >= 0 && leafX < ISLAND_SIZE && leafZ >= 0 && leafZ < ISLAND_SIZE) {
            voxelMap.setVoxel('Ground', { position: { x: leafX, y: leafY, z: leafZ }, blockId: 7 });
          }
        }
      }
    }
  }
}
