// ─── Rune Resource Data ───
// Maps rune simulation ResourceId to inventory item IDs (BlockId).
// Pure data — no ECS, no Three.js.

import { ResourceId, type ResourceIdValue } from "../../engine/runes/resource.ts";
import { BlockId } from "../../world/blocks.ts";

/**
 * Map from rune simulation ResourceId to inventory BlockId/ItemId.
 * Each resource generated by rune circuits has a corresponding
 * block or item that enters the player's inventory.
 */
const RESOURCE_TO_ITEM: Record<ResourceIdValue, number> = {
	[ResourceId.Ore]: BlockId.IronOre,
	[ResourceId.Ingot]: BlockId.CopperOre, // smelted ore
	[ResourceId.Wheat]: BlockId.Cranberry, // closest food crop
	[ResourceId.Bread]: BlockId.Cranberry, // cooked food
	[ResourceId.Wood]: BlockId.Wood,
	[ResourceId.Planks]: BlockId.Planks,
	[ResourceId.CrystalShard]: BlockId.Crystal,
	[ResourceId.CrystalLens]: BlockId.Glass,
	[ResourceId.Sand]: BlockId.Sand,
	[ResourceId.Glass]: BlockId.Glass,
	[ResourceId.RawMeat]: BlockId.Mushroom, // closest food item
	[ResourceId.CookedMeat]: BlockId.Mushroom, // cooked food
};

/** Convert a rune simulation ResourceId to the corresponding inventory item ID. */
export function resourceToItemId(resourceId: ResourceIdValue): number {
	return RESOURCE_TO_ITEM[resourceId] ?? BlockId.Stone;
}

/** Particle color for resource pickup effects (gold sparkle). */
export const PICKUP_PARTICLE_COLOR = 0xffd700;

/** Number of particles spawned on pickup. */
export const PICKUP_PARTICLE_COUNT = 4;
